name: Publiser Spørretimen
on:
  push:
    branches: [gh-pages]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Hent nettsiden
        uses: actions/checkout@v4
      - name: Klargjør Pages
        uses: actions/configure-pages@v5
      - name: Last opp nettsiden
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Publiser
        id: deployment
        uses: actions/deploy-pages@v4
